// Curated dictionary of common skills used to scan resumes and job descriptions.
// Each entry: canonical display name, list of matchable aliases (lowercase), and a category
// used to group missing skills and pick a relevant suggestion.

const SKILLS_DB = [
  // Programming Languages
  { name: "Python", aliases: ["python"], category: "Programming Languages" },
  { name: "JavaScript", aliases: ["javascript", "js", "ecmascript", "es6"], category: "Programming Languages" },
  { name: "TypeScript", aliases: ["typescript", "ts"], category: "Programming Languages" },
  { name: "Java", aliases: ["java"], category: "Programming Languages" },
  { name: "C++", aliases: ["c++", "cpp"], category: "Programming Languages" },
  { name: "C#", aliases: ["c#", "csharp", "c sharp"], category: "Programming Languages" },
  { name: "C", aliases: ["c programming", " c language"], category: "Programming Languages" },
  { name: "Go", aliases: ["golang", "go language"], category: "Programming Languages" },
  { name: "Rust", aliases: ["rust"], category: "Programming Languages" },
  { name: "Ruby", aliases: ["ruby"], category: "Programming Languages" },
  { name: "PHP", aliases: ["php"], category: "Programming Languages" },
  { name: "Swift", aliases: ["swift"], category: "Programming Languages" },
  { name: "Kotlin", aliases: ["kotlin"], category: "Programming Languages" },
  { name: "SQL", aliases: ["sql"], category: "Programming Languages" },
  { name: "R", aliases: ["r programming", "r language"], category: "Programming Languages" },
  { name: "Scala", aliases: ["scala"], category: "Programming Languages" },
  { name: "MATLAB", aliases: ["matlab"], category: "Programming Languages" },
  { name: "Perl", aliases: ["perl"], category: "Programming Languages" },
  { name: "Shell Scripting", aliases: ["bash", "shell scripting", "shell script"], category: "Programming Languages" },
  { name: "Dart", aliases: ["dart"], category: "Programming Languages" },

  // Frontend & Web
  { name: "HTML", aliases: ["html", "html5"], category: "Frontend & Web" },
  { name: "CSS", aliases: ["css", "css3"], category: "Frontend & Web" },
  { name: "Sass/SCSS", aliases: ["sass", "scss"], category: "Frontend & Web" },
  { name: "React", aliases: ["react.js", "reactjs", "react"], category: "Frontend & Web" },
  { name: "Angular", aliases: ["angular.js", "angularjs", "angular"], category: "Frontend & Web" },
  { name: "Vue.js", aliases: ["vue.js", "vuejs", "vue"], category: "Frontend & Web" },
  { name: "Next.js", aliases: ["next.js", "nextjs"], category: "Frontend & Web" },
  { name: "Svelte", aliases: ["svelte"], category: "Frontend & Web" },
  { name: "Redux", aliases: ["redux"], category: "Frontend & Web" },
  { name: "Tailwind CSS", aliases: ["tailwind", "tailwind css"], category: "Frontend & Web" },
  { name: "Bootstrap", aliases: ["bootstrap"], category: "Frontend & Web" },
  { name: "jQuery", aliases: ["jquery"], category: "Frontend & Web" },
  { name: "Webpack", aliases: ["webpack"], category: "Frontend & Web" },
  { name: "GraphQL", aliases: ["graphql"], category: "Frontend & Web" },
  { name: "REST APIs", aliases: ["rest api", "restful api", "rest apis", "restful apis"], category: "Frontend & Web" },
  { name: "Responsive Design", aliases: ["responsive design", "responsive web design"], category: "Frontend & Web" },

  // Backend & Frameworks
  { name: "Node.js", aliases: ["node.js", "nodejs", "node js"], category: "Backend & Frameworks" },
  { name: "Express.js", aliases: ["express.js", "expressjs", "express"], category: "Backend & Frameworks" },
  { name: "Django", aliases: ["django"], category: "Backend & Frameworks" },
  { name: "Flask", aliases: ["flask"], category: "Backend & Frameworks" },
  { name: "FastAPI", aliases: ["fastapi"], category: "Backend & Frameworks" },
  { name: "Spring Boot", aliases: ["spring boot", "spring framework"], category: "Backend & Frameworks" },
  { name: "Ruby on Rails", aliases: ["ruby on rails", "rails"], category: "Backend & Frameworks" },
  { name: "ASP.NET", aliases: ["asp.net", "dot net", ".net"], category: "Backend & Frameworks" },
  { name: "Laravel", aliases: ["laravel"], category: "Backend & Frameworks" },
  { name: "Microservices", aliases: ["microservices", "microservice architecture"], category: "Backend & Frameworks" },
  { name: "gRPC", aliases: ["grpc"], category: "Backend & Frameworks" },

  // Databases
  { name: "MySQL", aliases: ["mysql"], category: "Databases" },
  { name: "PostgreSQL", aliases: ["postgresql", "postgres"], category: "Databases" },
  { name: "MongoDB", aliases: ["mongodb", "mongo"], category: "Databases" },
  { name: "Redis", aliases: ["redis"], category: "Databases" },
  { name: "SQLite", aliases: ["sqlite"], category: "Databases" },
  { name: "Oracle Database", aliases: ["oracle database", "oracle db", "oracle sql"], category: "Databases" },
  { name: "Cassandra", aliases: ["cassandra"], category: "Databases" },
  { name: "DynamoDB", aliases: ["dynamodb"], category: "Databases" },
  { name: "Elasticsearch", aliases: ["elasticsearch", "elastic search"], category: "Databases" },
  { name: "Firebase", aliases: ["firebase"], category: "Databases" },
  { name: "Database Design", aliases: ["database design", "data modeling"], category: "Databases" },

  // Cloud & DevOps
  { name: "AWS", aliases: ["aws", "amazon web services"], category: "Cloud & DevOps" },
  { name: "Microsoft Azure", aliases: ["azure", "microsoft azure"], category: "Cloud & DevOps" },
  { name: "Google Cloud Platform", aliases: ["gcp", "google cloud platform", "google cloud"], category: "Cloud & DevOps" },
  { name: "Docker", aliases: ["docker"], category: "Cloud & DevOps" },
  { name: "Kubernetes", aliases: ["kubernetes", "k8s"], category: "Cloud & DevOps" },
  { name: "Terraform", aliases: ["terraform"], category: "Cloud & DevOps" },
  { name: "Jenkins", aliases: ["jenkins"], category: "Cloud & DevOps" },
  { name: "CI/CD", aliases: ["ci/cd", "ci cd", "continuous integration", "continuous deployment", "continuous delivery"], category: "Cloud & DevOps" },
  { name: "Ansible", aliases: ["ansible"], category: "Cloud & DevOps" },
  { name: "Git", aliases: ["git", "version control"], category: "Cloud & DevOps" },
  { name: "GitHub Actions", aliases: ["github actions"], category: "Cloud & DevOps" },
  { name: "Linux", aliases: ["linux", "unix"], category: "Cloud & DevOps" },
  { name: "Nginx", aliases: ["nginx"], category: "Cloud & DevOps" },
  { name: "Serverless", aliases: ["serverless", "lambda", "aws lambda"], category: "Cloud & DevOps" },
  { name: "Infrastructure as Code", aliases: ["infrastructure as code", "cloudformation"], category: "Cloud & DevOps" },
  { name: "Monitoring & Observability", aliases: ["prometheus", "grafana", "observability", "monitoring tools"], category: "Cloud & DevOps" },

  // Data & Machine Learning
  { name: "Machine Learning", aliases: ["machine learning", "ml"], category: "Data & Machine Learning" },
  { name: "Deep Learning", aliases: ["deep learning"], category: "Data & Machine Learning" },
  { name: "TensorFlow", aliases: ["tensorflow"], category: "Data & Machine Learning" },
  { name: "PyTorch", aliases: ["pytorch"], category: "Data & Machine Learning" },
  { name: "scikit-learn", aliases: ["scikit-learn", "sklearn"], category: "Data & Machine Learning" },
  { name: "Pandas", aliases: ["pandas"], category: "Data & Machine Learning" },
  { name: "NumPy", aliases: ["numpy"], category: "Data & Machine Learning" },
  { name: "Data Analysis", aliases: ["data analysis", "data analytics"], category: "Data & Machine Learning" },
  { name: "Data Visualization", aliases: ["data visualization", "data viz"], category: "Data & Machine Learning" },
  { name: "Tableau", aliases: ["tableau"], category: "Data & Machine Learning" },
  { name: "Power BI", aliases: ["power bi", "powerbi"], category: "Data & Machine Learning" },
  { name: "Natural Language Processing", aliases: ["natural language processing", "nlp"], category: "Data & Machine Learning" },
  { name: "Computer Vision", aliases: ["computer vision"], category: "Data & Machine Learning" },
  { name: "Statistics", aliases: ["statistics", "statistical analysis"], category: "Data & Machine Learning" },
  { name: "Big Data", aliases: ["big data"], category: "Data & Machine Learning" },
  { name: "Apache Spark", aliases: ["apache spark", "spark"], category: "Data & Machine Learning" },
  { name: "Hadoop", aliases: ["hadoop"], category: "Data & Machine Learning" },
  { name: "ETL Pipelines", aliases: ["etl", "etl pipelines", "data pipelines"], category: "Data & Machine Learning" },
  { name: "A/B Testing", aliases: ["a/b testing", "ab testing", "split testing"], category: "Data & Machine Learning" },

  // Mobile
  { name: "Android Development", aliases: ["android development", "android"], category: "Mobile" },
  { name: "iOS Development", aliases: ["ios development", "ios"], category: "Mobile" },
  { name: "React Native", aliases: ["react native"], category: "Mobile" },
  { name: "Flutter", aliases: ["flutter"], category: "Mobile" },
  { name: "SwiftUI", aliases: ["swiftui"], category: "Mobile" },
  { name: "Jetpack Compose", aliases: ["jetpack compose"], category: "Mobile" },

  // Testing & QA
  { name: "Unit Testing", aliases: ["unit testing", "unit tests"], category: "Testing & QA" },
  { name: "Selenium", aliases: ["selenium"], category: "Testing & QA" },
  { name: "Jest", aliases: ["jest"], category: "Testing & QA" },
  { name: "Cypress", aliases: ["cypress"], category: "Testing & QA" },
  { name: "Test Automation", aliases: ["test automation", "automated testing"], category: "Testing & QA" },
  { name: "Manual QA", aliases: ["manual qa", "manual testing", "quality assurance"], category: "Testing & QA" },
  { name: "Postman", aliases: ["postman"], category: "Testing & QA" },
  { name: "Load Testing", aliases: ["load testing", "performance testing"], category: "Testing & QA" },

  // Design & Product
  { name: "UI/UX Design", aliases: ["ui/ux", "ui ux", "ux design", "ui design", "user experience design", "user interface design"], category: "Design & Product" },
  { name: "Figma", aliases: ["figma"], category: "Design & Product" },
  { name: "Adobe XD", aliases: ["adobe xd"], category: "Design & Product" },
  { name: "Sketch", aliases: ["sketch app"], category: "Design & Product" },
  { name: "Product Management", aliases: ["product management"], category: "Design & Product" },
  { name: "Agile Methodology", aliases: ["agile", "agile methodology", "agile methodologies"], category: "Design & Product" },
  { name: "Scrum", aliases: ["scrum"], category: "Design & Product" },
  { name: "Kanban", aliases: ["kanban"], category: "Design & Product" },
  { name: "Jira", aliases: ["jira"], category: "Design & Product" },
  { name: "Wireframing", aliases: ["wireframing", "wireframes", "prototyping"], category: "Design & Product" },
  { name: "User Research", aliases: ["user research"], category: "Design & Product" },

  // Soft Skills
  { name: "Communication", aliases: ["communication skills", "communication"], category: "Soft Skills" },
  { name: "Leadership", aliases: ["leadership"], category: "Soft Skills" },
  { name: "Teamwork", aliases: ["teamwork", "team player", "collaboration"], category: "Soft Skills" },
  { name: "Problem Solving", aliases: ["problem solving", "problem-solving"], category: "Soft Skills" },
  { name: "Project Management", aliases: ["project management"], category: "Soft Skills" },
  { name: "Time Management", aliases: ["time management"], category: "Soft Skills" },
  { name: "Critical Thinking", aliases: ["critical thinking"], category: "Soft Skills" },
  { name: "Adaptability", aliases: ["adaptability", "flexibility"], category: "Soft Skills" },
  { name: "Presentation Skills", aliases: ["presentation skills", "public speaking"], category: "Soft Skills" },
  { name: "Negotiation", aliases: ["negotiation"], category: "Soft Skills" },
  { name: "Mentoring", aliases: ["mentoring", "coaching"], category: "Soft Skills" },
  { name: "Stakeholder Management", aliases: ["stakeholder management"], category: "Soft Skills" },

  // Marketing & Business
  { name: "SEO", aliases: ["seo", "search engine optimization"], category: "Marketing & Business" },
  { name: "SEM", aliases: ["sem", "search engine marketing"], category: "Marketing & Business" },
  { name: "Google Analytics", aliases: ["google analytics"], category: "Marketing & Business" },
  { name: "Content Marketing", aliases: ["content marketing"], category: "Marketing & Business" },
  { name: "Social Media Marketing", aliases: ["social media marketing"], category: "Marketing & Business" },
  { name: "Email Marketing", aliases: ["email marketing"], category: "Marketing & Business" },
  { name: "CRM", aliases: ["crm", "customer relationship management"], category: "Marketing & Business" },
  { name: "Salesforce", aliases: ["salesforce", "sfdc"], category: "Marketing & Business" },
  { name: "Market Research", aliases: ["market research"], category: "Marketing & Business" },
  { name: "Copywriting", aliases: ["copywriting"], category: "Marketing & Business" },
  { name: "Brand Strategy", aliases: ["brand strategy", "branding"], category: "Marketing & Business" },
  { name: "Digital Marketing", aliases: ["digital marketing"], category: "Marketing & Business" },
  { name: "Google Ads", aliases: ["google ads", "adwords"], category: "Marketing & Business" },
  { name: "Meta / Facebook Ads", aliases: ["facebook ads", "meta ads"], category: "Marketing & Business" },

  // Security
  { name: "Cybersecurity", aliases: ["cybersecurity", "cyber security", "information security"], category: "Security" },
  { name: "Penetration Testing", aliases: ["penetration testing", "pen testing", "pentesting"], category: "Security" },
  { name: "Network Security", aliases: ["network security"], category: "Security" },
  { name: "Cryptography", aliases: ["cryptography"], category: "Security" },
  { name: "SOC Operations", aliases: ["soc operations", "security operations center"], category: "Security" },
  { name: "SIEM", aliases: ["siem"], category: "Security" },
  { name: "Vulnerability Assessment", aliases: ["vulnerability assessment", "vulnerability management"], category: "Security" },
  { name: "Identity and Access Management", aliases: ["identity and access management", "iam"], category: "Security" },
  { name: "OWASP", aliases: ["owasp"], category: "Security" },

  // Tools & Productivity
  { name: "Microsoft Excel", aliases: ["excel", "microsoft excel"], category: "Tools & Productivity" },
  { name: "Microsoft PowerPoint", aliases: ["powerpoint", "microsoft powerpoint"], category: "Tools & Productivity" },
  { name: "Microsoft Word", aliases: ["microsoft word"], category: "Tools & Productivity" },
  { name: "Confluence", aliases: ["confluence"], category: "Tools & Productivity" },
  { name: "Slack", aliases: ["slack"], category: "Tools & Productivity" },
  { name: "Notion", aliases: ["notion"], category: "Tools & Productivity" },
  { name: "Google Workspace", aliases: ["google workspace", "google docs", "google sheets"], category: "Tools & Productivity" },

  // More Cloud & DevOps / Data tooling
  { name: "Snowflake", aliases: ["snowflake"], category: "Cloud & DevOps" },
  { name: "Apache Kafka", aliases: ["kafka", "apache kafka"], category: "Cloud & DevOps" },
  { name: "Apache Airflow", aliases: ["airflow", "apache airflow"], category: "Cloud & DevOps" },
  { name: "dbt", aliases: ["dbt"], category: "Data & Machine Learning" },
  { name: "Looker", aliases: ["looker"], category: "Data & Machine Learning" },
  { name: "GitLab", aliases: ["gitlab"], category: "Cloud & DevOps" },
  { name: "Bitbucket", aliases: ["bitbucket"], category: "Cloud & DevOps" },
  { name: "Chef", aliases: ["chef automation", "chef/puppet"], category: "Cloud & DevOps" },
  { name: "Puppet", aliases: ["puppet"], category: "Cloud & DevOps" },
  { name: "VMware", aliases: ["vmware"], category: "Cloud & DevOps" },
  { name: "Active Directory", aliases: ["active directory"], category: "Cloud & DevOps" },
  { name: "ITIL", aliases: ["itil"], category: "Cloud & DevOps" },
  { name: "Splunk", aliases: ["splunk"], category: "Cloud & DevOps" },
  { name: "Redshift", aliases: ["redshift", "amazon redshift"], category: "Databases" },
  { name: "BigQuery", aliases: ["bigquery", "big query"], category: "Databases" },

  // More Programming / Engineering
  { name: "Objective-C", aliases: ["objective-c", "objective c"], category: "Programming Languages" },
  { name: "Unity", aliases: ["unity engine", "unity3d", "unity 3d"], category: "Programming Languages" },
  { name: "Unreal Engine", aliases: ["unreal engine"], category: "Programming Languages" },
  { name: "Blockchain", aliases: ["blockchain"], category: "Programming Languages" },
  { name: "Solidity", aliases: ["solidity"], category: "Programming Languages" },
  { name: "WordPress", aliases: ["wordpress"], category: "Frontend & Web" },
  { name: "Shopify", aliases: ["shopify"], category: "Frontend & Web" },

  // Sales & Customer Service
  { name: "Sales", aliases: ["sales"], category: "Sales & Customer Service" },
  { name: "Cold Calling", aliases: ["cold calling", "cold outreach"], category: "Sales & Customer Service" },
  { name: "Lead Generation", aliases: ["lead generation"], category: "Sales & Customer Service" },
  { name: "Account Management", aliases: ["account management"], category: "Sales & Customer Service" },
  { name: "Customer Service", aliases: ["customer service"], category: "Sales & Customer Service" },
  { name: "Customer Support", aliases: ["customer support"], category: "Sales & Customer Service" },
  { name: "Technical Support", aliases: ["technical support", "help desk"], category: "Sales & Customer Service" },
  { name: "Upselling", aliases: ["upselling", "cross-selling"], category: "Sales & Customer Service" },
  { name: "Client Relations", aliases: ["client relations", "client relationship management"], category: "Sales & Customer Service" },
  { name: "Sales Forecasting", aliases: ["sales forecasting"], category: "Sales & Customer Service" },
  { name: "HubSpot", aliases: ["hubspot"], category: "Sales & Customer Service" },
  { name: "Zendesk", aliases: ["zendesk"], category: "Sales & Customer Service" },

  // Finance & Accounting
  { name: "Accounting", aliases: ["accounting"], category: "Finance & Accounting" },
  { name: "Bookkeeping", aliases: ["bookkeeping"], category: "Finance & Accounting" },
  { name: "Financial Modeling", aliases: ["financial modeling", "financial modelling"], category: "Finance & Accounting" },
  { name: "Financial Analysis", aliases: ["financial analysis"], category: "Finance & Accounting" },
  { name: "Budgeting", aliases: ["budgeting"], category: "Finance & Accounting" },
  { name: "Forecasting", aliases: ["forecasting"], category: "Finance & Accounting" },
  { name: "Accounts Payable", aliases: ["accounts payable"], category: "Finance & Accounting" },
  { name: "Accounts Receivable", aliases: ["accounts receivable"], category: "Finance & Accounting" },
  { name: "Auditing", aliases: ["auditing", "internal audit"], category: "Finance & Accounting" },
  { name: "Tax Preparation", aliases: ["tax preparation", "tax filing"], category: "Finance & Accounting" },
  { name: "QuickBooks", aliases: ["quickbooks"], category: "Finance & Accounting" },
  { name: "SAP", aliases: ["sap"], category: "Finance & Accounting" },
  { name: "GAAP", aliases: ["gaap"], category: "Finance & Accounting" },

  // HR & Recruiting
  { name: "Recruiting", aliases: ["recruiting", "recruitment"], category: "HR & Recruiting" },
  { name: "Talent Acquisition", aliases: ["talent acquisition"], category: "HR & Recruiting" },
  { name: "Onboarding", aliases: ["onboarding"], category: "HR & Recruiting" },
  { name: "Employee Relations", aliases: ["employee relations"], category: "HR & Recruiting" },
  { name: "HRIS", aliases: ["hris"], category: "HR & Recruiting" },
  { name: "Payroll", aliases: ["payroll"], category: "HR & Recruiting" },
  { name: "Performance Management", aliases: ["performance management"], category: "HR & Recruiting" },
  { name: "Compensation & Benefits", aliases: ["compensation and benefits", "compensation & benefits"], category: "HR & Recruiting" },
  { name: "Workday", aliases: ["workday"], category: "HR & Recruiting" },

  // Operations & Supply Chain
  { name: "Supply Chain Management", aliases: ["supply chain management", "supply chain"], category: "Operations & Supply Chain" },
  { name: "Logistics", aliases: ["logistics"], category: "Operations & Supply Chain" },
  { name: "Inventory Management", aliases: ["inventory management"], category: "Operations & Supply Chain" },
  { name: "Procurement", aliases: ["procurement"], category: "Operations & Supply Chain" },
  { name: "Warehouse Management", aliases: ["warehouse management system", "wms"], category: "Operations & Supply Chain" },
  { name: "Six Sigma", aliases: ["six sigma"], category: "Operations & Supply Chain" },
  { name: "Lean Manufacturing", aliases: ["lean manufacturing", "lean methodology"], category: "Operations & Supply Chain" },
  { name: "Quality Control", aliases: ["quality control"], category: "Operations & Supply Chain" },
  { name: "Vendor Management", aliases: ["vendor management"], category: "Operations & Supply Chain" },

  // Healthcare
  { name: "Patient Care", aliases: ["patient care"], category: "Healthcare" },
  { name: "Electronic Health Records", aliases: ["electronic health records", "ehr", "emr"], category: "Healthcare" },
  { name: "HIPAA Compliance", aliases: ["hipaa"], category: "Healthcare" },
  { name: "Clinical Research", aliases: ["clinical research"], category: "Healthcare" },
  { name: "Medical Coding", aliases: ["medical coding", "icd-10"], category: "Healthcare" },
  { name: "Nursing", aliases: ["nursing"], category: "Healthcare" },
  { name: "CPR Certification", aliases: ["cpr certified", "cpr certification"], category: "Healthcare" },

  // Education & Training
  { name: "Curriculum Development", aliases: ["curriculum development"], category: "Education & Training" },
  { name: "Lesson Planning", aliases: ["lesson planning"], category: "Education & Training" },
  { name: "Classroom Management", aliases: ["classroom management"], category: "Education & Training" },
  { name: "Instructional Design", aliases: ["instructional design"], category: "Education & Training" },
  { name: "Tutoring", aliases: ["tutoring"], category: "Education & Training" },
  { name: "E-Learning", aliases: ["e-learning", "elearning"], category: "Education & Training" },

  // Legal & Compliance
  { name: "Contract Management", aliases: ["contract management"], category: "Legal & Compliance" },
  { name: "Legal Research", aliases: ["legal research"], category: "Legal & Compliance" },
  { name: "Regulatory Compliance", aliases: ["regulatory compliance"], category: "Legal & Compliance" },
  { name: "Risk Management", aliases: ["risk management"], category: "Legal & Compliance" },
  { name: "GDPR Compliance", aliases: ["gdpr"], category: "Legal & Compliance" },

  // Manufacturing & Engineering
  { name: "CAD", aliases: ["cad", "computer-aided design"], category: "Manufacturing & Engineering" },
  { name: "AutoCAD", aliases: ["autocad"], category: "Manufacturing & Engineering" },
  { name: "SolidWorks", aliases: ["solidworks"], category: "Manufacturing & Engineering" },
  { name: "Mechanical Engineering", aliases: ["mechanical engineering"], category: "Manufacturing & Engineering" },
  { name: "Electrical Engineering", aliases: ["electrical engineering"], category: "Manufacturing & Engineering" },
  { name: "CNC Machining", aliases: ["cnc machining", "cnc"], category: "Manufacturing & Engineering" },
  { name: "Process Improvement", aliases: ["process improvement"], category: "Manufacturing & Engineering" },
];
